### ISSUE TITLE
After traveling to/from a different time zone, weather alerts are scheduled at the wrong time

### ISSUE THREAD

**Issue by stkent** [rstockbridge/OhNoSnow#1]
After traveling to/from a time zone 5 hours ahead of my own, weather alerts are scheduled at the wrong time (~2pm rather than ~7pm):

![Screenshot_20200204-143558](https://user-images.githubusercontent.com/6463980/73844612-e5b73880-47ee-11ea-986d-55e3b738e482.png)

Alerts also occurred at the wrong time while traveling (~12am rather than ~7pm).

**Comment by rstockbridge** [comment]
@stkent thanks for letting me know!

**Comment by rstockbridge** [comment]
A little bird helped me resolve this! 🎉
